### ISSUE TITLE
The component renders a string

### ISSUE THREAD

**Issue by smakosh** [bukinoshita/react-hash-avatar#13]
Not sure what's the cause but here's a screenshot

![Screen Shot 2020-09-20 at 14 41 38](https://user-images.githubusercontent.com/20082141/93712705-66912d80-fb4f-11ea-98c5-21401ec61dee.png)

And here's how I'm using it

```jsx
import React from 'react'
import ReactHashAvatar from "react-hash-avatar";

const Example = () => <ReactHashAvatar name="i" width="90px" height="90px" />
```

**Comment by smakosh** [comment]
@bukinoshita 👀

**Comment by bukinoshita** [comment]
Can you try using the `react-hash-avatar@1.0.0-beta.0`?

**Comment by smakosh** [comment]
Works fine on a new project, probably doesn't when next-images plugin is used without the svg library, I'll close this for now since it's unrelated.

Good library @bukinoshita
